# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1st_inform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import *
from schedule import *
import datetime

class inform1(QtWidgets.QWidget):

    layout = QtWidgets.QStackedLayout()
    newUserData = data()
    f1Status = "xxxoxxxoxxxoxxxoxxxoxxxoxxxoxx"
    f2Status = "xxxoxxxoxxxoxxxoxxxoxxxoxxxoxx"
    f3Status = "xxxoxxoxxxoxxoxxxoxxoxxxoxxoxx"
    schedule = 0

    def __init__(self):
        super(inform1, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        #Form.setObjectName("Form")
        #Form.resize(400, 620)
        #Form.setStyleSheet("background-color: rgb(202, 226, 255);")
        #-------------
        self.setAutoFillBackground(True)
        palette = self.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor("#D2EDFF"))
        self.setPalette(palette)
        #-------------
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(8, 8, 8);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 170, 51, 41))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 260, 71, 41))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.wi = QtWidgets.QLineEdit(Form)
        self.wi.setGeometry(QtCore.QRect(200, 180, 151, 31))
        self.wi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.wi.setObjectName("wi")
        self.wa = QtWidgets.QLineEdit(Form)
        self.wa.setGeometry(QtCore.QRect(200, 260, 151, 31))
        self.wa.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.wa.setObjectName("wa")
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(250, 470, 93, 28))
        self.okButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.okButton.setObjectName("okButton")
        self.okButton.clicked.connect(self.calbmi)
        self.okButton.clicked.connect(self.collect_data)
        self.okButton.clicked.connect(self.switchPanel)
        self.Male = QtWidgets.QRadioButton(Form)
        self.Male.setGeometry(QtCore.QRect(60, 420, 95, 20))
        self.Male.setObjectName("Male")
        self.Female = QtWidgets.QRadioButton(Form)
        self.Female.setGeometry(QtCore.QRect(250, 420, 95, 20))
        self.Female.setObjectName("Female")
        self.hi = QtWidgets.QLineEdit(Form)
        self.hi.setGeometry(QtCore.QRect(200, 340, 151, 31))
        self.hi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hi.setObjectName("hi")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 340, 71, 41))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Information"))
        self.label_2.setText(_translate("Form", "Weight"))
        self.label_3.setText(_translate("Form", "Waistline"))
        self.okButton.setText(_translate("Form", "OK"))
        self.Male.setText(_translate("Form", "Male"))
        self.Female.setText(_translate("Form", "Female"))
        self.label_4.setText(_translate("Form", "Hieght"))

    def calbmi(self):
            wi = float(self.wi.text())
            hi = float(self.hi.text())
            bmi = wi/((hi/100)**2)
            if bmi < 18.5 :
                program = 'f1'
                status = self.f1Status
            elif bmi > 23 :
                program = 'f3'
                status = self.f3Status
            else:
                program = 'f2'
                status = self.f2Status

            self.newUserData.program = program
            self.newUserData.status = status
            self.newUserData.firstDate = str(datetime.date.today())
            self.newUserData.latestDay = "0"
            self.newUserData.weight = self.wi.text()
            self.newUserData.waistline = self.wa.text()
            filename = self.newUserData.username # +'.txt'
            fw0 = open("progress/" + filename, 'x')
            fw = open("progress/" + filename,'w')
            fw.write(self.newUserData.username + '|')
            fw.write(self.newUserData.program + '|')
            fw.write(self.newUserData.status + '|')
            fw.write(self.newUserData.firstDate + "|")
            fw.write(self.newUserData.latestDay+'\n')
            fw.write(self.newUserData.weight+'|')
            fw.write(self.newUserData.waistline )    
            fw.close()
            fw0.close()
            wtaFile = open("progress/" + filename + "Progress", 'x')
            wtaFile = open("progress/" + filename + "Progress", 'a')
            wtaFile.write(self.newUserData.weight + '|' + self.newUserData.waistline + '\n')
            wtaFile.close()
        #newwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

            print(bmi,program,self.newUserData.firstDate)

    def collect_data(self):
            listwi = []
            listhi = []
            listwa = []
            listwi.append(float(self.wi.text()))
            listhi.append(float(self.hi.text()))
            listwa.append(float(self.wa.text()))
    def addLayout(self, stackedLayout):
        self.layout = stackedLayout        

    def addNewUserData(self, newUserData):
        self.newUserData = newUserData

    def switchPanel(self):
        schedule.setExPlan()
        self.layout.setCurrentIndex(4)

    def addSchedulePanel(self, schedule):
        self.schedule = schedule

    

            




"""if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())"""
