# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import *
from schedule import *


class inform(QtWidgets.QWidget):

    layout = QtWidgets.QStackedLayout()
    listwi = []
    listwa = []
    userData = data()
    schedule = 0

    def __init__(self):
        super(inform, self).__init__()
        self.setupUi(self)
    
    def setupUi(self, Form):
        #Form.setObjectName("Form")
        #Form.resize(400, 620)
        #Form.setStyleSheet("background-color: rgb(205, 238, 255);")
        #-------------
        self.setAutoFillBackground(True)
        palette = self.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor("#D2EDFF"))
        self.setPalette(palette)
        #-------------
        self.waistline = QtWidgets.QLineEdit(Form)
        self.waistline.setGeometry(QtCore.QRect(190, 250, 151, 31))
        self.waistline.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.waistline.setObjectName("waistline")
        self.weight = QtWidgets.QLineEdit(Form)
        self.weight.setGeometry(QtCore.QRect(190, 170, 151, 31))
        self.weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.weight.setObjectName("weight")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(110, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(8, 8, 8);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 71, 41))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 51, 41))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(260, 330, 93, 28))
        self.okButton.setObjectName("okButton")
        self.okButton.clicked.connect(self.collect_data)
        self.okButton.clicked.connect(self.switchPanel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Information"))
        self.label_3.setText(_translate("Form", "Waistline"))
        self.label_2.setText(_translate("Form", "Weight"))
        self.okButton.setText(_translate("Form", "OK"))

    def collect_data(self):
        self.userData.weight = self.weight.text()
        self.userData.waistline = self.waistline.text()
        
         
        filename  = "progress/" + self.userData.username + "Progress"
        try:
            fw = open(filename, "x")
        except:
            print(filename + " exists")
        finally:
            fw = open(filename,'a')
            fw.write(self.userData.weight + '|' + self.userData.waistline + '\n')
            fw.close()

    def addLayout(self, stackedLayout):
        self.layout = stackedLayout

    def switchPanel(self):
        self.schedule.setExPlan()
        self.layout.setCurrentIndex(4)

    def addUserData(self, userData):
        self.userData = userData

    def addSchedulePanel(self, schedule):
        self.schedule = schedule

"""if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())"""
