# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import *


class register(QtWidgets.QWidget):
        
    layout = QtWidgets.QStackedLayout()
    newUserData = data()

    def __init__(self):
        super(register, self).__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        #Form.setObjectName("Form")
        #Form.resize(400, 620)
        #Form.setStyleSheet("background-color: rgb(207, 236, 255);")
        #-------------
        self.setAutoFillBackground(True)
        palette = self.palette()
        palette.setColor(QtGui.QPalette.ColorRole.Window, QtGui.QColor("#D2EDFF"))
        self.setPalette(palette)
        #-------------
        self.user = QtWidgets.QLineEdit(Form)
        self.user.setGeometry(QtCore.QRect(210, 141, 151, 31))
        self.user.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.user.setObjectName("user")
        self.pw = QtWidgets.QLineEdit(Form)
        self.pw.setGeometry(QtCore.QRect(210, 251, 151, 31))
        self.pw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pw.setObjectName("pw")
        self.pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cpw = QtWidgets.QLineEdit(Form)
        self.cpw.setGeometry(QtCore.QRect(210, 361, 151, 31))
        self.cpw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpw.setObjectName("cpw")
        self.cpw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginButton = QtWidgets.QPushButton(Form)
        self.loginButton.setGeometry(QtCore.QRect(280, 460, 93, 28))
        self.loginButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.toLogin)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 250, 81, 41))
        self.label_3.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(8, 8, 8);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 140, 51, 41))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"\n"
"color: rgb(0, 0, 127);")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 360, 151, 41))
        self.label_4.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 127);")
        self.label_4.setObjectName("label_4")
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(60, 460, 93, 28))
        self.okButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.okButton.setObjectName("okButton")
        self.okButton.clicked.connect(self.reg)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.loginButton.setText(_translate("Form", "Login"))
        self.label_3.setText(_translate("Form", " Password"))
        self.label.setText(_translate("Form", "Register"))
        self.label_2.setText(_translate("Form", "User"))
        self.label_4.setText(_translate("Form", " Confirm Password"))
        self.okButton.setText(_translate("Form", "OK"))

    def reg(self):
        newuser = self.user.text()
        pw = self.pw.text()
        cpw = self.cpw.text()
        userp = open('authen/userpassword.txt','r')
        adduser = open('authen/userpassword.txt','a')
        userpp = userp.readlines()
        l = []
        userAccount = []
        userPassword = []
        for i in userpp:
                l.append(i.strip())
                userpp = l
        for i in range(len(userpp)):
                if i%2 == 0:
                        userAccount.append(userpp[i])
                if i%2 == 1:
                        userPassword.append(userpp[i])
        if newuser not in userAccount:
                if cpw == pw:
                        adduser.write(newuser+'\n')
                        adduser.write(pw+'\n')
                        self.newUserData.username = newuser
                        self.toInform1()
                        
                #newwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
                        
                else:
                        self.cpw.setText('')
                        self.pw.setText('')
        else:
                self.user.setText('')
        
    def addLayout(self, stackedLayout):
        self.layout = stackedLayout

    def toLogin(self):
        self.layout.setCurrentIndex(0)

    def toInform1(self):
        self.layout.setCurrentIndex(2)    
    
    def addNewUserData(self, newUserData):
        self.newUserData = newUserData

    
        

        
        


"""if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())"""
