# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import *
import matplotlib.pyplot as plt

class schedule(QtWidgets.QWidget):
    
    todayPragram = []
    day = "01"
    exNameLabel = ""
    exPictureLabel = ""
    exTimerLabel = ""
    startButton = ""
    animationWidth = 400
    animationHeight = 400
    userData = data()
    buttonIndex = 1
    graphPanel = 0

    def __init__(self):
        super(schedule, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        #MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(1000, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 991, 721))
        self.label.setStyleSheet("background-image: url(image/f1.jpg)")
        print(self.userData.program)
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 230, 161, 60))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 208, 251,0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.WeightGraph)
        #self.pushButton_2.clicked.connect(self.WaistlinetGraph)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 465, 161, 60))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 208, 251,0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.WaistlinetGraph)
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(62, 100, 101, 101))
        self.b1.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b1.setText("")
        self.b1.setObjectName("b1")
        self.b1.clicked.connect(self.toExPanel01)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(170, 100, 111, 101))
        self.b2.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b2.setText("")
        self.b2.setObjectName("b2")
        self.b2.clicked.connect(self.toExPanel02)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(290, 100, 111, 111))
        self.b3.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b3.setText("")
        self.b3.setObjectName("b3")
        self.b3.clicked.connect(self.toExPanel03)
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(410, 100, 101, 101))
        self.b4.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b4.setText("")
        self.b4.setObjectName("b4")
        self.b4.clicked.connect(self.toExPanel04)
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(520, 100, 111, 101))
        self.b5.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b5.setText("")
        self.b5.setObjectName("b5")
        self.b5.clicked.connect(self.toExPanel05)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(640, 100, 111, 101))
        self.b6.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b6.setText("")
        self.b6.setObjectName("b6")
        self.b6.clicked.connect(self.toExPanel06)
        self.b12 = QtWidgets.QPushButton(self.centralwidget)
        self.b12.setGeometry(QtCore.QRect(640, 220, 111, 101))
        self.b12.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b12.setText("")
        self.b12.setObjectName("b12")
        self.b12.clicked.connect(self.toExPanel12)
        self.b11 = QtWidgets.QPushButton(self.centralwidget)
        self.b11.setGeometry(QtCore.QRect(520, 220, 111, 101))
        self.b11.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b11.setText("")
        self.b11.setObjectName("b11")
        self.b11.clicked.connect(self.toExPanel11)
        self.b10 = QtWidgets.QPushButton(self.centralwidget)
        self.b10.setGeometry(QtCore.QRect(410, 220, 101, 101))
        self.b10.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b10.setText("")
        self.b10.setObjectName("b10")
        self.b10.clicked.connect(self.toExPanel10)
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(290, 220, 111, 101))
        self.b9.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b9.setText("")
        self.b9.setObjectName("b9")
        self.b9.clicked.connect(self.toExPanel09)
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(170, 220, 111, 101))
        self.b8.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b8.setText("")
        self.b8.setObjectName("b8")
        self.b8.clicked.connect(self.toExPanel08)
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(60, 220, 101, 101))
        self.b7.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b7.setText("")
        self.b7.setObjectName("b7")
        self.b7.clicked.connect(self.toExPanel07)
        self.b13 = QtWidgets.QPushButton(self.centralwidget)
        self.b13.setGeometry(QtCore.QRect(60, 340, 101, 101))
        self.b13.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b13.setText("")
        self.b13.setObjectName("b13")
        self.b13.clicked.connect(self.toExPanel13)
        self.b14 = QtWidgets.QPushButton(self.centralwidget)
        self.b14.setGeometry(QtCore.QRect(170, 340, 111, 101))
        self.b14.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b14.setText("")
        self.b14.setObjectName("b14")
        self.b14.clicked.connect(self.toExPanel14)
        self.b15 = QtWidgets.QPushButton(self.centralwidget)
        self.b15.setGeometry(QtCore.QRect(290, 340, 111, 101))
        self.b15.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b15.setText("")
        self.b15.setObjectName("b15")
        self.b15.clicked.connect(self.toExPanel15)
        self.b16 = QtWidgets.QPushButton(self.centralwidget)
        self.b16.setGeometry(QtCore.QRect(410, 340, 101, 101))
        self.b16.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b16.setText("")
        self.b16.setObjectName("b16")
        self.b16.clicked.connect(self.toExPanel16)
        self.b17 = QtWidgets.QPushButton(self.centralwidget)
        self.b17.setGeometry(QtCore.QRect(520, 340, 111, 101))
        self.b17.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b17.setText("")
        self.b17.setObjectName("b17")
        self.b17.clicked.connect(self.toExPanel17)
        self.b18 = QtWidgets.QPushButton(self.centralwidget)
        self.b18.setGeometry(QtCore.QRect(640, 340, 111, 101))
        self.b18.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b18.setText("")
        self.b18.setObjectName("b18")
        self.b18.clicked.connect(self.toExPanel18)
        self.b19 = QtWidgets.QPushButton(self.centralwidget)
        self.b19.setGeometry(QtCore.QRect(60, 460, 101, 101))
        self.b19.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b19.setText("")
        self.b19.setObjectName("b19")
        self.b19.clicked.connect(self.toExPanel19)
        self.b20 = QtWidgets.QPushButton(self.centralwidget)
        self.b20.setGeometry(QtCore.QRect(170, 460, 111, 101))
        self.b20.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b20.setText("")
        self.b20.setObjectName("b20")
        self.b20.clicked.connect(self.toExPanel20)
        self.b21 = QtWidgets.QPushButton(self.centralwidget)
        self.b21.setGeometry(QtCore.QRect(290, 460, 111, 101))
        self.b21.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b21.setText("")
        self.b21.setObjectName("b21")
        self.b21.clicked.connect(self.toExPanel21)
        self.b22 = QtWidgets.QPushButton(self.centralwidget)
        self.b22.setGeometry(QtCore.QRect(410, 460, 101, 101))
        self.b22.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b22.setText("")
        self.b22.setObjectName("b22")
        self.b22.clicked.connect(self.toExPanel22)
        self.b23 = QtWidgets.QPushButton(self.centralwidget)
        self.b23.setGeometry(QtCore.QRect(520, 460, 111, 101))
        self.b23.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b23.setText("")
        self.b23.setObjectName("b23")
        self.b23.clicked.connect(self.toExPanel23)
        self.b24 = QtWidgets.QPushButton(self.centralwidget)
        self.b24.setGeometry(QtCore.QRect(640, 460, 111, 101))
        self.b24.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b24.setText("")
        self.b24.setObjectName("b24")
        self.b24.clicked.connect(self.toExPanel24)
        self.b25 = QtWidgets.QPushButton(self.centralwidget)
        self.b25.setGeometry(QtCore.QRect(60, 580, 101, 101))
        self.b25.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b25.setText("")
        self.b25.setObjectName("b25")
        self.b25.clicked.connect(self.toExPanel25)
        self.b26 = QtWidgets.QPushButton(self.centralwidget)
        self.b26.setGeometry(QtCore.QRect(170, 580, 111, 101))
        self.b26.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b26.setText("")
        self.b26.setObjectName("b26")
        self.b26.clicked.connect(self.toExPanel26)
        self.b27 = QtWidgets.QPushButton(self.centralwidget)
        self.b27.setGeometry(QtCore.QRect(290, 580, 111, 101))
        self.b27.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b27.setText("")
        self.b27.setObjectName("b27")
        self.b27.clicked.connect(self.toExPanel27)
        self.b28 = QtWidgets.QPushButton(self.centralwidget)
        self.b28.setGeometry(QtCore.QRect(410, 580, 101, 101))
        self.b28.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b28.setText("")
        self.b28.setObjectName("b28")
        self.b28.clicked.connect(self.toExPanel28)
        self.b29 = QtWidgets.QPushButton(self.centralwidget)
        self.b29.setGeometry(QtCore.QRect(520, 580, 111, 101))
        self.b29.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b29.setText("")
        self.b29.setObjectName("b29")
        self.b29.clicked.connect(self.toExPanel29)
        self.b30 = QtWidgets.QPushButton(self.centralwidget)
        self.b30.setGeometry(QtCore.QRect(640, 580, 111, 101))
        self.b30.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.b30.setText("")
        self.b30.clicked.connect(self.toExPanel30)
        self.b30.setObjectName("b30")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        ##self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        #self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.enableButton()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Weight Graph"))
        self.pushButton_3.setText(_translate("MainWindow", "Waistline Graph"))
        
    def setExPlan(self):
        if(self.userData.program == "f1"):
            self.label.setStyleSheet("background-image: url(image/f1.jpg)")
        elif(self.userData.program == "f2"):
            self.label.setStyleSheet("background-image: url(image/f2.jpg)")
        else:
            self.label.setStyleSheet("background-image: url(image/f3.jpg)")
        self.enableButton()

    def setTodayProgram(self, program):
        self.todayPragram = program
        firstProgram = self.todayPragram[0]
        programName = firstProgram[3]
        programDuration = firstProgram[2]
        movie = QMovie("exgif/"+programName + ".gif")
        movie.start()
        self.exPictureLabel.setMovie(movie)
        s=movie.currentImage().size()
        self.animationWidth = s.width()
        self.animationHeight = s.height()
        self.exNameLabel.setText(programName.capitalize())
        self.exTimerLabel.setText(programDuration)

    def getAnimationWidth(self):
        return self.animationWidth

    def getAnimationHeight(self):
        return self.animationHeight

    def addLayout(self, stackedLayout):
        self.layout = stackedLayout

    def switchPanel(self):
        self.layout.setCurrentIndex(6)

    def toExPanel(self):
        self.layout.setCurrentIndex(5)

    def toExPanel01(self):
        self.userData.latestDay = "00"
        self.layout.setCurrentIndex(5)
    
    def toExPanel02(self):
        self.userData.latestDay = "01"
        self.layout.setCurrentIndex(5)

    def toExPanel03(self):
        self.userData.latestDay = "02"
        self.layout.setCurrentIndex(5)

    def toExPanel04(self):
        self.userData.latestDay = "03"
        self.layout.setCurrentIndex(5)
    
    def toExPanel05(self):
        self.userData.latestDay = "04"
        self.layout.setCurrentIndex(5)
    
    def toExPanel06(self):
        self.userData.latestDay = "05"
        self.layout.setCurrentIndex(5)

    def toExPanel07(self):
        self.userData.latestDay = "06"
        self.layout.setCurrentIndex(5)

    def toExPanel08(self):
        self.userData.latestDay = "07"
        self.layout.setCurrentIndex(5)

    def toExPanel09(self):
        self.userData.latestDay = "08"
        self.layout.setCurrentIndex(5)

    def toExPanel10(self):
        self.userData.latestDay = "09"
        self.layout.setCurrentIndex(5)

    def toExPanel11(self):
        self.userData.latestDay = "10"
        self.layout.setCurrentIndex(5)

    def toExPanel12(self):
        self.userData.latestDay = "11"
        self.layout.setCurrentIndex(5)

    def toExPanel13(self):
        self.userData.latestDay = "12"
        self.layout.setCurrentIndex(5)

    def toExPanel14(self):
        self.userData.latestDay = "13"
        self.layout.setCurrentIndex(5)
    def toExPanel15(self):
        self.userData.latestDay = "14"
        self.layout.setCurrentIndex(5)
    def toExPanel16(self):
        self.userData.latestDay = "15"
        self.layout.setCurrentIndex(5)
    def toExPanel17(self):
        self.userData.latestDay = "16"
        self.layout.setCurrentIndex(5)
    def toExPanel18(self):
        self.userData.latestDay = "17"
        self.layout.setCurrentIndex(5)
    def toExPanel19(self):
        self.userData.latestDay = "18"
        self.layout.setCurrentIndex(5)
    def toExPanel20(self):
        self.userData.latestDay = "19"
        self.layout.setCurrentIndex(5)
    def toExPanel21(self):
        self.userData.latestDay = "20"
        self.layout.setCurrentIndex(5)
    def toExPanel22(self):
        self.userData.latestDay = "21"
        self.layout.setCurrentIndex(5)
    def toExPanel23(self):
        self.userData.latestDay = "22"
        self.layout.setCurrentIndex(5)
    def toExPanel24(self):
        self.userData.latestDay = "23"
        self.layout.setCurrentIndex(5)
    def toExPanel25(self):
        self.userData.latestDay = "24"
        self.layout.setCurrentIndex(5)
    def toExPanel26(self):
        self.userData.latestDay = "25"
        self.layout.setCurrentIndex(5)
    def toExPanel27(self):
        self.userData.latestDay = "26"
        self.layout.setCurrentIndex(5)
    def toExPanel28(self):
        self.userData.latestDay = "27"
        self.layout.setCurrentIndex(5)
    def toExPanel29(self):
        self.userData.latestDay = "28"
        self.layout.setCurrentIndex(5)
    def toExPanel30(self):
        self.userData.latestDay = "29"
        self.layout.setCurrentIndex(5)

    def enableButton(self):
        status = self.userData.status
        if(status.__len__()<30):
            status = "xxxoxxxoxxxoxxxoxxxoxxxoxxxoxx"
        btn = [self.b1,self.b2,self.b3,self.b4,self.b5,self.b6,self.b7,self.b8,self.b9,self.b10,self.b11,self.b12,self.b13,self.b14,self.b15,self.b16,self.b17,self.b18,self.b19,self.b20,self.b21,self.b22,self.b23,self.b24,self.b25,self.b26,self.b27,self.b28,self.b29,self.b30]
        for i in range(btn.__len__()):
            if(status[i] == "o"):
                btn[i].setEnabled(False)
    
    def addUserData(self, userData):
        self.userData = userData


    def WeightGraph(self):
        self.loadGraph()
        wi = self.userData.weight
        wi = wi.split('|')
        wix = list()
        for w in range(wi.__len__() - 1):
            wix.append(wi[w])
        a = []
        
        for i in range(len(wix) + 1):
            if i != 0:
                a.append(i)
        print(wix)
        
        plt.gca().invert_yaxis()
        plt.plot(a,wix)
        plt.title('Weight Graph') 
        plt.xlabel('day')
        plt.ylabel('Weight(Kgs)')
        plt.show()

    def WaistlinetGraph(self):
        self.loadGraph()
        wa = self.userData.waistline
        wa = wa.split('|')
        wax = list()
        for w in range(wa.__len__() - 1):
            wax.append(wa[w])
        a = []
        
        for i in range(len(wax) + 1):
            if i != 0:
                a.append(i)
        print(a)
                
        plt.gca().invert_yaxis()
        plt.plot(a,wax)
        plt.title('Waistline Graph') 
        plt.xlabel('day')
        plt.ylabel('Waist(Inches)')
        plt.show()

    def loadGraph(self):
        file = open("progress/" + self.userData.username + "Progress", "r")
        data = file.readlines()
        wt = ''
        wa = ''
        i = 0
        for lineData in data:
            wtwadata = lineData.split('|')
            wt = wt + wtwadata[0]
            wa = wa + wtwadata[1]
            if(i < data.__len__()):
                wt = wt + '|'
                wa = wa + '|'
            i += 1
        self.userData.weight = wt
        self.userData.waistline = wa
        file.close()
    


"""if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())"""
